import Provider from '@/theme/Provider'
import Layout from '@/template/layout/RootLayout'
import NextAuth from '@/auth/NextAuth'
import UserProvider from '@/context/UserContext'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="es">
      {/*
        <head /> will contain the components returned by the nearest parent
        head.tsx. Find out more at https://beta.nextjs.org/docs/api-reference/file-conventions/head
      */}
      <head />
      <body>
        <NextAuth>
          <UserProvider>
          <Provider>
            <Layout>
              {children}
            </Layout>
          </Provider>
          </UserProvider>
        </NextAuth>
      </body>
    </html >

  )
}
