version: '3'
services:
  psql:
    image: postgres:15.3-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
    - POSTGRES_PASSWORD=demo
    - POSTGRES_USER=demo
    - POSTGRES_DB=UserContextDb  
    volumes:
      - psql_data:/var/lib/postgresql/data
volumes:
  psql_data:
    driver: local