CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230717135109_Demo') THEN
    CREATE TABLE "Category" (
        "Id" uuid NOT NULL,
        "Name" VARCHAR NOT NULL,
        "Status" integer NOT NULL,
        CONSTRAINT "PK_Category" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230717135109_Demo') THEN
    CREATE TABLE "Service" (
        "Id" uuid NOT NULL,
        "Name" VARCHAR NOT NULL,
        "Status" integer NOT NULL,
        CONSTRAINT "PK_Service" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230717135109_Demo') THEN
    CREATE TABLE "Type" (
        "Id" uuid NOT NULL,
        "Name" VARCHAR NOT NULL,
        "Status" integer NOT NULL,
        "TypeIcon" VARCHAR NULL,
        CONSTRAINT "PK_Type" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230717135109_Demo') THEN
    CREATE TABLE "SubCategory" (
        "Id" uuid NOT NULL,
        "Name" VARCHAR NOT NULL,
        "Status" integer NOT NULL,
        "CategoryId" uuid NULL,
        CONSTRAINT "PK_SubCategory" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SubCategory_Category_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Category" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230717135109_Demo') THEN
    CREATE TABLE "Specialization" (
        "Id" uuid NOT NULL,
        "Name" VARCHAR NOT NULL,
        "SpecializationIcon" VARCHAR NULL,
        "Status" integer NOT NULL,
        "CompanyTypeId" uuid NULL,
        CONSTRAINT "PK_Specialization" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Specialization_Type_CompanyTypeId" FOREIGN KEY ("CompanyTypeId") REFERENCES "Type" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230717135109_Demo') THEN
    CREATE TABLE "Requirement" (
        "ServiceId" uuid NOT NULL,
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CategoryId" uuid NOT NULL,
        "SubCategoryId" uuid NULL,
        CONSTRAINT "PK_Requirement" PRIMARY KEY ("ServiceId", "Id"),
        CONSTRAINT "FK_Requirement_Category_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Category" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Requirement_Service_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Service" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Requirement_SubCategory_SubCategoryId" FOREIGN KEY ("SubCategoryId") REFERENCES "SubCategory" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230717135109_Demo') THEN
    CREATE TABLE "Area" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TypeId" uuid NOT NULL,
        "SpecializationId" uuid NULL,
        "CategoryId" uuid NULL,
        "Discriminator" text NOT NULL,
        "ServiceId" uuid NULL,
        CONSTRAINT "PK_Area" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Area_Category_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Category" ("Id"),
        CONSTRAINT "FK_Area_Service_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Service" ("Id"),
        CONSTRAINT "FK_Area_Specialization_SpecializationId" FOREIGN KEY ("SpecializationId") REFERENCES "Specialization" ("Id"),
        CONSTRAINT "FK_Area_Type_TypeId" FOREIGN KEY ("TypeId") REFERENCES "Type" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230717135109_Demo') THEN
    CREATE INDEX "IX_Area_CategoryId" ON "Area" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230717135109_Demo') THEN
    CREATE INDEX "IX_Area_ServiceId" ON "Area" ("ServiceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230717135109_Demo') THEN
    CREATE INDEX "IX_Area_SpecializationId" ON "Area" ("SpecializationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230717135109_Demo') THEN
    CREATE INDEX "IX_Area_TypeId" ON "Area" ("TypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230717135109_Demo') THEN
    CREATE INDEX "IX_Requirement_CategoryId" ON "Requirement" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230717135109_Demo') THEN
    CREATE INDEX "IX_Requirement_SubCategoryId" ON "Requirement" ("SubCategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230717135109_Demo') THEN
    CREATE INDEX "IX_Specialization_CompanyTypeId" ON "Specialization" ("CompanyTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230717135109_Demo') THEN
    CREATE INDEX "IX_SubCategory_CategoryId" ON "SubCategory" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230717135109_Demo') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20230717135109_Demo', '7.0.3');
    END IF;
END $EF$;
COMMIT;

