import Provider from '@/theme/Provider'
import NextAuth from '@/auth/NextAuth'
import CompanyRootLayout from '@/template/layout/CompanyRootLayout'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="es">
      {/*
        <head /> will contain the components returned by the nearest parent
        head.tsx. Find out more at https://beta.nextjs.org/docs/api-reference/file-conventions/head
      */}
      <head />
      <body>
        <NextAuth>
          <Provider>
            <CompanyRootLayout>
              {children}
            </CompanyRootLayout>
          </Provider>
        </NextAuth>
      </body>
    </html >

  )
}
